### ISSUE TITLE
github/smarthook.js is sending replying with 500 from the webtask

### ISSUE THREAD

**Issue by ArSn** [auth0/webtask-scripts#4]
I used this guide to set up a simple github-webhook-connected webtask: https://webtask.io/docs/sample_github

It works fine up to the point where the response of the webtask is read by GitHub. This leads to the task working perfectly fine, but the very unattractive side effect that the callback for error and/or success messages does not work properly.

**Steps to reproduce**
1. Follow guide that is linked above
2. Check deliveries in the settings of your github repo
3. Find HTPP {500} responses here

Log of **one** execution of the webhook:
```
[20:11:01.939Z]  INFO wt: connected to streaming logs (container=wt-koljaz-***-0)
[20:11:12.779Z]  INFO wt: webtask container assigned
[20:11:13.880Z]  INFO wt: 
    {
      "code": 500,
      "error": "Script generated an unhandled asynchronous exception.",
      "details": "ReferenceError: writeHead is not defined",
      "name": "ReferenceError",
      "message": "writeHead is not defined",
      "stack": "ReferenceError: writeHead is not defined\n    at args (/data/smarthook.js:99:21)\n    at Request.eval [as _callback] (eval at <anonymous> (/data/smarthook.js:55:69), <anonymous>:49:28)\n    at Request.self.callback (/data/_verquire/request/2.56.0/node_modules/request/request.js:354:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1207:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1153:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)"
    }
[20:11:13.880Z]  INFO wt: 
    {
      "code": 500,
      "error": "Script generated an unhandled asynchronous exception.",
      "details": "ReferenceError: writeHead is not defined",
      "name": "ReferenceError",
      "message": "writeHead is not defined",
      "stack": "ReferenceError: writeHead is not defined\n    at args (/data/smarthook.js:99:21)\n    at Request.eval [as _callback] (eval at <anonymous> (/data/smarthook.js:55:69), <anonymous>:49:28)\n    at Request.self.callback (/data/_verquire/request/2.56.0/node_modules/request/request.js:354:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1207:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1153:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)"
    }
[20:11:13.882Z]  INFO wt: 
    {
      "code": 500,
      "error": "Script generated an unhandled asynchronous exception.",
      "details": "ReferenceError: writeHead is not defined",
      "name": "ReferenceError",
      "message": "writeHead is not defined",
      "stack": "ReferenceError: writeHead is not defined\n    at args (/data/smarthook.js:99:21)\n    at Request.eval [as _callback] (eval at <anonymous> (/data/smarthook.js:55:69), <anonymous>:49:28)\n    at Request.self.callback (/data/_verquire/request/2.56.0/node_modules/request/request.js:354:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1207:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1153:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)"
    }
[20:11:13.882Z]  INFO wt: 
    {
      "code": 500,
      "error": "Script generated an unhandled asynchronous exception.",
      "details": "ReferenceError: writeHead is not defined",
      "name": "ReferenceError",
      "message": "writeHead is not defined",
      "stack": "ReferenceError: writeHead is not defined\n    at args (/data/smarthook.js:99:21)\n    at Request.eval [as _callback] (eval at <anonymous> (/data/smarthook.js:55:69), <anonymous>:49:28)\n    at Request.self.callback (/data/_verquire/request/2.56.0/node_modules/request/request.js:354:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1207:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1153:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)"
    }
[20:11:13.883Z]  INFO wt: 
    Code generated an uncaught exception:  ReferenceError: writeHead is not defined
        at args (/data/smarthook.js:99:21)
        at Request.eval [as _callback] (eval at <anonymous> (/data/smarthook.js:55:69), <anonymous>:49:28)
        at Request.self.callback (/data/_verquire/request/2.56.0/node_modules/request/request.js:354:22)
        at Request.emit (events.js:110:17)
        at Request.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1207:14)
        at Request.emit (events.js:129:20)
        at IncomingMessage.<anonymous> (/data/_verquire/request/2.56.0/node_modules/request/request.js:1153:12)
        at IncomingMessage.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickDomainCallback (node.js:381:11)
[20:11:14.533Z]  INFO wt: webtask container recycled
```

The problem here seems to be that the writeHead() is not a function in this scope, but rather has to be called on the response (`res`). Adding this actually solves the issue, the log looks afterwards like:
```
[20:31:30.122Z]  INFO wt: connected to streaming logs (container=wt-koljaz-***-0)
[20:32:35.974Z]  INFO wt: webtask container assigned
[20:33:25.738Z]  INFO wt: webtask container recycled
```

And the responses are with valid codes, for both errors and successes. I will send a pull request to fix this shortly.

**Comment by LuxDie** [comment]
@ArSn Thanks! I'm using your version and it works fine.

**Comment by chenkie** [comment]
@ArSn your PR has been merged :)

**Comment by ArSn** [comment]
@chenkie Awesome, thanks!
